YouTiming
    .constant('arcfname', 'archive.json')
    .constant('archive_neg', 'archive-neg')
    .constant('archive_page', 'archive')
    .constant('archive_pos', 'archive-pos')
    .constant('clicklist', 'clickfromlist')
    .constant('clickpage', 'clickfrompage')
    .constant('histdir', '/model/archive/')
    .constant('home_neg', 'home-neg')
    .constant('home_pos', 'home-pos')
    .constant('home_page', 'home')
    .constant('modeldir', '/model/')
    .constant('portfname', 'active.json')
    .constant('tickerPerPage', 1)
    .constant('weekfname', '/model/weekly-date.json')
    .constant('yang', 'yang')
    .constant('yangPageActiveClass', 'btn-info')
    .constant('yin', 'yin')
    .constant('yinPageActiveClass', 'btn-warning')
    // for metaphore
    .constant('guidance', 'Typical')
    .constant('miss', 'Non-typical')
    ;